dragoon_admin_login:
    pattern: /login
    defaults: { _controller:DragoonAdminBundle:Security:login }

dragoon_admin_login_check:
    pattern: /login_check

dragoon_admin_logout:
    pattern: /logout

dragoon_admin_dashboard:
    pattern: /dash
    defaults: { _controller:DragoonAdminBundle:Index:index }
    
dragoon_admin_user_edit:
    pattern: /user_profile
    defaults: { _controller:DragoonAdminBundle:User:form }

dragoon_admin_list:
    pattern: /{entity}/list
    defaults: { _controller:DragoonAdminBundle:Base:list }

dragoon_admin_create:
    pattern: /{entity}/create
    defaults: { _controller:DragoonAdminBundle:Base:edit }

dragoon_admin_edit:
    pattern: /{entity}/edit/{id}
    defaults: { _controller:DragoonAdminBundle:Base:edit }
    requirements:
        id: \d+

dragoon_admin_delete:
    pattern: /{entity}/delete/{id}
    defaults: { _controller:DragoonAdminBundle:Base:edit }
    requirements:
        id: \d+
    
dragoon_film_add_dvdfr:
    pattern: /{entity}/create/dvdfr
    defaults: { _controller:DragoonAdminBundle:Dvdfr:search }
    
dragoon_dvdfr_list:
    pattern: /dvdfr/list/{search}
    defaults: { _controller:DragoonAdminBundle:Dvdfr:list }
    
dragoon_dvdfr_view:
    pattern: /dvdfr/view/{id}
    defaults: { _controller:DragoonAdminBundle:Dvdfr:view }
    requirements:
        id: \d+

dragoon_dvdfr_add:
    pattern: /dvdfr/add/{id}
    defaults: { _controller:DragoonAdminBundle:Dvdfr:add }
    requirements:
        id: \d+