dragoon_admin_login:
    pattern: /login
    defaults: { _controller:DragoonAdminBundle:Login:index }
    
dragoon_admin_dashboard:
    pattern: /dash
    defaults: { _controller:DragoonAdminBundle:Index:index }