parameters:
#    dragoon_admin.example.class: Dragoon\AdminBundle\Example

services:
#    dragoon_admin.example:
#        class: %dragoon_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
