#http://symfony.com/fr/doc/current/book/security.html
security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /admin/login
                check_path:  /admin/login_check
                default_target_path: /admin/dash
            logout:      
                path:  /admin/logout
                target: /admin/login
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 jours en secondes
                path:     /
                domain:   ~ # Prend la valeur par défaut du domaine courant depuis $_SERVER
            

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
#       - { path: ^/admin/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/admin, roles: ROLE_ADMIN}

#    providers:
#        in_memory:
#             memory:
#                users:
#                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
#                    admin: { password: kitten, roles: 'ROLE_ADMIN' }
    providers:
        main:
            entity: { class: Dragoon\AdminBundle\Entity\User, property: username }

    encoders:
        Dragoon\AdminBundle\Entity\User: plaintext